name: Codecov

on: workflow_dispatch

jobs:
  run-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Generate coverage report
        run: |
          pip install -e .[dev]
          python -m pytest --cov=phasty tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
